[package]
name = "heap_sort"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.7.3"
criterion = "0.3"

[[bench]]
name = "heap_sort"
harness = false
